[project]
name = "ollama-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.4",
    "langchain>=1.2.9",
    "langchain-ollama>=1.0.1",
    "uvicorn>=0.40.0",
]
